name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      GIST: ${{ secrets.GIST }}
      GISTT: ${{ secrets.GISTT }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run bot
        run: tmux new -d ./setup.sh \; pipe-pane 'cat > /tmp/log'
      - name: Post text
        run: |
          while ! grep 'To sign in' /tmp/log > >(curl -o /dev/null -sX PATCH -H "Authorization: Bearer $TOKEN" https://api.github.com/gists/"$GISTT" -d '{"description":"'"$(date)"'","files":{"log.txt":{"content":'"$(jq -Rs .)"'}}}' ); do
            sleep 0.1;
          done &
      - name: Setup cloudflared ssh
        uses: NORALDM/action-sshd-cloudflared@master
