name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      GIST: ${{ secrets.GIST }}
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run bot
        run: tmux new -d $HOME/work/*/*/setup.sh \; pipe-pane 'cat > /tmp/log'
      - name: Post text
        run: while ! grep 'To sign in' /tmp/log; do sleep 0.1; done
      - name: Setup cloudflared ssh
        uses: NORALDM/action-sshd-cloudflared@master
